### ISSUE TITLE
Posible error on Manual formula 363 and 364 ccx manual 2.20

### ISSUE THREAD

**Issue by disla2** [Dhondtguido/CalculiX#23]
![screenshot 104](https://user-images.githubusercontent.com/126724892/222271992-6d6c5a3a-c948-4d56-8df9-354044477731.jpg)

Subindex is recommended on Manual formula 363 to avoid confusion between the second order Taylor approximation of the logarithmic Strain and the Eulerian Strain. One is computed using initial length Lo and Eulerian using final length L.

**Comment by FEA-eng** [comment]
There are quite a few typos and mistakes in the ccx manual. @Dhondtguido said that he will create a separate repository with the documentation where we could create issues (or possible PRs) to correct such mistakes. Unfortunately, this repository hasn't been created yet.

**Comment by Dhondtguido** [comment]
Hi,
your remark is correct, my expansion of the Eulerian strain was incorrect (the coefficient of the second term should be -3/2 instead of -1/2). Therefore, the Eulerian and logarithmic strain can be quite different. I decided to define the *DEFORMATION PLASTICITY routine as a Abaqus umat routine using logarithmic strain (using the umat_abaqusnl.f routine in CalculiX). Now the results are more in line with Abaqus. This new approach will be available in the next CalculiX version.
Thanks for pointing this out.
Guido
